"""Constants for the Homeduino 433 MHz RF transceiver integration."""

from typing import Final

DOMAIN: Final = "homeduino"

CONF_ENTRY_TYPE: Final = "entry_type"
CONF_ENTRY_TYPE_TRANSCEIVER: Final = "transceiver"
CONF_ENTRY_TYPE_RF_DEVICE: Final = "rf_device"
CONF_ENTRY_TYPE_LOCAL_DEVICE: Final = "local_device"
CONF_SERIAL_PORT: Final = "serial_port"
CONF_BAUD_RATE: Final = "baud_rate"
CONF_RECEIVE_PIN: Final = "receive_pin"
CONF_SEND_PIN: Final = "send_pin"
CONF_RF_DEVICE_TYPE: Final = "rf_device_type"
CONF_RF_PROTOCOL: Final = "rf_protocol"
CONF_RF_ID: Final = "rf_id"
CONF_RF_UNIT: Final = "rf_unit"
CONF_RF_ID_IGNORE_ALL: Final = "rf_id_ignore_all"
CONF_RF_UNIT_EXTRAPOLATE: Final = "rf_unit_extrapolate"
CONF_LOCAL_DEVICE_GPIO: Final = "gpio"
CONF_LOCAL_DEVICE_TYPE: Final = "type"
CONF_LOCAL_DEVICE_TYPE_DHT11: Final = "local_dht11"
CONF_LOCAL_DEVICE_TYPE_DHT22: Final = "local_dht22"
CONF_LOCAL_DEVICE_TYPE_DS18B20: Final = "local_ds18b20"
CONF_LOCAL_DEVICE_TYPE_ANALOG_INPUT: Final = "local_analog_input"
CONF_LOCAL_DEVICE_TYPE_DIGITAL_INPUT: Final = "local_digital_input"
CONF_LOCAL_DEVICE_TYPE_DIGITAL_OUTPUT: Final = "local_digital_output"
CONF_LOCAL_DEVICE_TYPE_PWM_OUTPUT: Final = "local_pwm_output"
CONF_LOCAL_DEVICE_INTERVAL: Final = "interval"
