"""Constants for the Homeduino 433 MHz RF transceiver integration."""
DOMAIN = "homeduino"

CONF_ENTRY_TYPE = "entry_type"
CONF_ENTRY_TYPE_TRANSCEIVER = "transceiver"
CONF_ENTRY_TYPE_RF_DEVICE = "rf_device"
CONF_SERIAL_PORT = "serial_port"
CONF_MANUAL_PATH = "manual_path"
CONF_RECEIVE_PIN = "receive_pin"
CONF_SEND_PIN = "send_pin"
CONF_RF_DEVICE_TYPE = "rf_device_type"
CONF_RF_PROTOCOL = "rf_protocol"
CONF_RF_ID = "rf_id"
CONF_RF_UNIT = "rf_unit"
CONF_RF_ID_IGNORE_ALL = "rf_id_ignore_all"
CONF_RF_UNIT_EXTRAPOLATE = "rf_unit_extrapolate"
